import type { CruiseLine } from "../types";

export const CRUISE_LINES: CruiseLine[] = [
  {
    id: "royal-caribbean",
    name: "Royal Caribbean International",
    shortName: "RCI",
    logo: "/images/cruise-lines/royal-caribbean.svg",
    color: "#0066CC",
    website: "https://www.royalcaribbean.com",
    loyaltyProgram: "Crown & Anchor Society",
  },
  {
    id: "carnival",
    name: "Carnival Cruise Line",
    shortName: "CCL",
    logo: "/images/cruise-lines/carnival.svg",
    color: "#003DA5",
    website: "https://www.carnival.com",
    loyaltyProgram: "VIFP Club",
  },
  {
    id: "norwegian",
    name: "Norwegian Cruise Line",
    shortName: "NCL",
    logo: "/images/cruise-lines/norwegian.svg",
    color: "#00BCD4",
    website: "https://www.ncl.com",
    loyaltyProgram: "Latitudes Rewards",
  },
  {
    id: "msc",
    name: "MSC Cruises",
    shortName: "MSC",
    logo: "/images/cruise-lines/msc.svg",
    color: "#003B73",
    website: "https://www.msccruises.com",
    loyaltyProgram: "MSC Voyagers Club",
  },
  {
    id: "celebrity",
    name: "Celebrity Cruises",
    shortName: "CEL",
    logo: "/images/cruise-lines/celebrity.svg",
    color: "#1C1C1C",
    website: "https://www.celebritycruises.com",
    loyaltyProgram: "Captain's Club",
  },
  {
    id: "princess",
    name: "Princess Cruises",
    shortName: "PCL",
    logo: "/images/cruise-lines/princess.svg",
    color: "#003366",
    website: "https://www.princess.com",
    loyaltyProgram: "Captain's Circle",
  },
  {
    id: "holland-america",
    name: "Holland America Line",
    shortName: "HAL",
    logo: "/images/cruise-lines/holland-america.svg",
    color: "#003B6F",
    website: "https://www.hollandamerica.com",
    loyaltyProgram: "Mariner Society",
  },
  {
    id: "disney",
    name: "Disney Cruise Line",
    shortName: "DCL",
    logo: "/images/cruise-lines/disney.svg",
    color: "#0066B2",
    website: "https://disneycruise.disney.go.com",
    loyaltyProgram: "Castaway Club",
  },
  {
    id: "virgin-voyages",
    name: "Virgin Voyages",
    shortName: "VV",
    logo: "/images/cruise-lines/virgin-voyages.svg",
    color: "#E4002B",
    website: "https://www.virginvoyages.com",
    loyaltyProgram: "The Sailing Club",
  },
];
